"""Migrate the frozen GSE171964 status while preserving hypothetical labels.

The v1.1 release uses the canonical replication-facet instance generated by
``build_bib_companion_evidence_contracts.py`` for reviewer-facing semantics.
"""

from __future__ import annotations

import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from pyfgsea.ted_evidence import ReplicationFacetInputs, assign_replication_facets


RESULTS = ROOT / "results" / "ted_gse171964_replication" / "analysis_v1"
STATUS_JSON = RESULTS / "replication_status.json"
STATUS_TSV = RESULTS / "replication_status.tsv"
CONFIG = ROOT / "config" / "ted_gse171964_replication_v1.yaml"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> None:
    status = json.loads(STATUS_JSON.read_text(encoding="utf-8"))
    config = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    donor_qc = pd.read_csv(RESULTS / "donor_blind_qc.tsv", sep="\t")
    n_evaluable = int(donor_qc["all_sample_qc_pass"].astype(bool).sum())
    minimum = int(config["design"]["minimum_evaluable_donors"])
    if n_evaluable != int(status["n_evaluable_donors"]):
        raise RuntimeError("persisted donor QC disagrees with replication_status.json")
    if n_evaluable >= minimum:
        raise RuntimeError("migration applies only to a failed eligibility prerequisite")
    if status.get("event_replication_status") not in {"failed", "not_evaluable"}:
        raise RuntimeError("unexpected pre-migration event replication status")

    old_status_sha256 = sha256(STATUS_JSON)
    facets = assign_replication_facets(
        ReplicationFacetInputs(
            event_analysis_complete=True,
            event_replication_tested=False,
            independent_cohort=True,
            same_event_family=True,
            early_activation_same_direction=None,
            recovery_same_direction=None,
            evaluable_donor_direction_fraction=None,
            family_adjusted_p=None,
            gates_frozen=True,
            additional_declared_gates_pass=False,
            outcome_analysis_complete=True,
            outcome_replication_tested=False,
            outcome_modality_compatible=False,
            outcome_type="protein",
        )
    )
    status.pop("event_statistical_test_status", None)
    status.pop("failure_reason", None)
    status.update(facets.as_dict())
    status.update(
        {
            "event_replication_attempt_status": "failed_at_eligibility_prerequisite",
            "event_replication_reason": "insufficient_frozen_QC_donors",
            "replication_attempt_display": (
                "eligibility failed | event test not_run | event replication not_evaluable | "
                "protein outcome replication not_tested"
            ),
            "status_schema_migration": "replication_eligibility_test_result_v2",
            "status_schema_migrated_at_utc": datetime.now(timezone.utc).isoformat(),
            "pre_migration_replication_status_sha256": old_status_sha256,
        }
    )
    status["protein_outcome"]["replication_status"] = facets.outcome_replication_status
    status["bounded_display_if_primary_E2_protein_passes"] = facets.display(
        "E2", within_study_outcome_status="passed"
    )
    STATUS_JSON.write_text(json.dumps(status, indent=2, allow_nan=False), encoding="utf-8")
    pd.DataFrame(
        [
            {
                "event_replication_eligibility_status": facets.event_replication_eligibility_status,
                "event_replication_test_status": facets.event_replication_test_status,
                "event_replication_status": facets.event_replication_status,
                "protein_outcome.replication_status": facets.outcome_replication_status,
                "event_replication_attempt_status": status["event_replication_attempt_status"],
                "event_replication_reason": status["event_replication_reason"],
                "bounded_display_if_primary_E2_protein_passes": status[
                    "bounded_display_if_primary_E2_protein_passes"
                ],
            }
        ]
    ).to_csv(STATUS_TSV, sep="\t", index=False)
    migration = {
        "migration": "replication_eligibility_test_result_v2",
        "migrated_at_utc": status["status_schema_migrated_at_utc"],
        "source_status_sha256": old_status_sha256,
        "migrated_status_sha256": sha256(STATUS_JSON),
        "migration_script": Path(__file__).relative_to(ROOT).as_posix(),
        "migration_script_sha256": sha256(Path(__file__)),
        "evaluable_donors": n_evaluable,
        "minimum_evaluable_donors": minimum,
        "event_replication_eligibility_status": facets.event_replication_eligibility_status,
        "event_replication_test_status": facets.event_replication_test_status,
        "event_replication_status": facets.event_replication_status,
        "event_replication_attempt_status": status["event_replication_attempt_status"],
        "event_replication_reason": status["event_replication_reason"],
        "thresholds_changed": False,
        "expression_statistics_run": False,
    }
    (RESULTS / "replication_status_schema_migration_v2.json").write_text(
        json.dumps(migration, indent=2), encoding="utf-8"
    )
    print(json.dumps(migration, indent=2))


if __name__ == "__main__":
    main()
